version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    build: ./app/database/
    image: "sqlite:latest"
    volumes:
      - ./test.db:/app/database/test.db
